--This is how you write comment in sql
--single line comment look like this
/*
 This is how you write multi
 line comment
 */
 -- each query you write knows as sql SELECT statement
-- * means all, here it means all columns
-- from some table that exist in the database
-- Just like Java
-- SQL Statements and in semi-colon : and it's mandatory
SELECT * FROM REGIONS ;
SELECT REGION_ID, REGION_NAME
FROM REGIONS;

--if you want to run second statement
--you just need to click the query to focus the cursor and click run
SELECT * FROM  COUNTRIES ;
SELECT COUNTRY_ID, COUNTRY_NAME, REGION_ID
FROM COUNTRIES;


SELECT * FROM  DEPARTMENTS ;
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID
FROM DEPARTMENTS;



SELECT * FROM EMPLOYEES ;
--restricting columns in the result
--SQL IS SPACE INSENSITIVE
SELECT FIRST_NAME
FROM EMPLOYEES ;
-- IF YOU WANT TO MORE THAN ONE COLUMNS CAN BE SPECIFIED SEPARATED BY COME
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES ;
SELECT FIRST_NAME, LAST_NAME, EMAIL
FROM EMPLOYEES ;



SELECT * FROM JOB_HISTORY ;
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY;
SELECT START_DATE, DEPARTMENT_ID
FROM JOB_HISTORY;


SELECT  * FROM LOCATIONS ;
SELECT LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID
FROM LOCATIONS;


SELECT  * FROM JOBS ;
SELECT JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY
FROM JOBS;







/*
 TASK : SELECT SPECIFIC COLUMNS FROM OTHER TABLES
 TO GET YOURSELF FAMILIAR WITH HR DATABASE
 */