
---------SUB QUERY : QUERY INSIDE ANOTHER QUERY------

--5 QUERY: MAX, MIN, SUM, AVG, COUNT

--FIND OUT MAX SALARY FROM EMPLOYEES
SELECT MAX(SALARY)
FROM EMPLOYEES;

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY = 24000;

-- WE HARD CODED THE VALUE OF 24000 WE GOT FROM FIST QUERY INTO SECOND QUERY
-- NOW JUST LIKE FUNCTION CALL WE CAN USE THIS QUERY
-- AS A BLOCK OF QUERY THAT GENERATE MAX SALARY ANYTIME
-- SO EVEN IF MAX SALARY CHANGE AT SOME POINT WE WOULD GET CORRECT RESULT
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY =(SELECT MAX(SALARY) FROM EMPLOYEES);

--FIND OUT THE NAME OF THE EMPLOYEE THAT MAKE LEAST SALARY
SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);


--FIND OUT THE NAME OF THE EMPLOYEE THAT MAKE MORE THAN AVERAGE SALARY
SELECT AVG(SALARY)
FROM EMPLOYEES;

SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY >(SELECT AVG(SALARY)
               FROM EMPLOYEES);


--DISPLAY ALL EMPLOYEES IF SALARY IS NOT 2400

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY!= 24000;

--AND FIND MAX SALARY
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY!= 24000;

--AND FIND SECOND MAX SALARY
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY!= (SELECT MAX(SALARY)FROM EMPLOYEES);